/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_monitoring_runtime_instrumentation_AllocationInstrumenter */

#ifndef _Included_com_google_monitoring_runtime_instrumentation_AllocationInstrumenter
#define _Included_com_google_monitoring_runtime_instrumentation_AllocationInstrumenter
#ifdef __cplusplus
extern "C" {
#endif
#undef com_google_monitoring_runtime_instrumentation_AllocationInstrumenter_is64bit
#define com_google_monitoring_runtime_instrumentation_AllocationInstrumenter_is64bit 1L
/*
 * Class:     com_google_monitoring_runtime_instrumentation_AllocationInstrumenter
 * Method:    dataCentric
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_google_monitoring_runtime_instrumentation_AllocationInstrumenter_dataCentric
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_google_monitoring_runtime_instrumentation_AllocationInstrumenter
 * Method:    clearTree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_monitoring_runtime_instrumentation_AllocationInstrumenter_clearTree
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
