/* DO NOT EDIT THIS FILE - it is machine generated */
#ifndef _ALLOCTION_INS_H
#define _ALLOCTION_INS_H

#include <jni.h>
#include <unordered_map>
#include "profiler.h"
#include "safe-sampling.h"
#include "splay.h"
#include "lock.h"
#include "ucontext.h"
#include "agent.h"
/* Header for class com_google_monitoring_runtime_instrumentation_AllocationInstrumenter */

#ifndef _Included_com_google_monitoring_runtime_instrumentation_AllocationInstrumenter
#define _Included_com_google_monitoring_runtime_instrumentation_AllocationInstrumenter
#ifdef __cplusplus
extern "C" {
#endif
#undef com_google_monitoring_runtime_instrumentation_AllocationInstrumenter_is64bit
#define com_google_monitoring_runtime_instrumentation_AllocationInstrumenter_is64bit 1L
/*
 * Class:     com_google_monitoring_runtime_instrumentation_AllocationInstrumenter
 * Method:    dataCentric
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_google_monitoring_runtime_instrumentation_AllocationInstrumenter_dataCentric
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_google_monitoring_runtime_instrumentation_AllocationInstrumenter
 * Method:    clearTree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_monitoring_runtime_instrumentation_AllocationInstrumenter_clearTree
  (JNIEnv *, jobject);

/*
 * Class:     com_google_monitoring_runtime_instrumentation_AllocationInstrumenter
 * Method:    removeReclaimedObjectInSplayTree
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_google_monitoring_runtime_instrumentation_AllocationInstrumenter_removeReclaimedObjectInSplayTree
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
#endif